environment:
  DEPLOY_KEY:
    secure: cva1Dwz5EzKZvpOnkEbv8atg6kX2nxVKxgcjFwfNwlhWMx0j4D0MumqR0OSbm44POVy5vtDbcleGKTfJ5RZKXzUZUnSG6ERCBSHxnEtVWuP3dkZpC/+RohRI4K0M9xtRh7bsExHHPSllS0IJR1/OyeeG1CbFYkU3b2joBpQnE/Mdi8paYRmK4akMhOolAKX0uEVCHhk4+H0u/FcScZBB3Pr1/4wzomGD+xn7nr54GRnFab9WO4yVXFz+C5POjoJ+s8Ffqk8gPIZvhfXEGXMotHeoW86gzcWb80oJ4NiCcG5/uddqnMUipOHO+acPrCAbZpnRKx96i6FSVUM0QpPH9L2aFXmLMwej65FzUU+iF4CNzBmjKG6jpoJmek/Xn9UVl6a1Ci8Ryq1v0TKEV7z3YTnfzI8ISImqYvG7DTwS8ax2e0FASBAU1YZJc+FPDBcwT8Gl5gvbPA5wOjyd5pxX47Ox1pF3v+AWVzdZRq+Gvbdh7rya6Xf5LdCelJTAIG6cxOEG21p4FYSEjOEIbxrlIB8TpJIzjMTXMK+uGe6uFA6FuCppPV2VqQIrP9H685gUYnkcPwbQOHRciw2fbnf9zzMqcYMaYsZyFHgHopShnhv3pEjTvaxWxZZcvag5S3oDorKAX1UwmWKuynvm6bCmWlD6at8OIp1AptFZDQbtyD+aFc2OYMUYT1EXzxkdVgwmv3svna06JUNrPAJUyoThdp9OCue9VrYvskYXT1p4TOEfN08E8PclEOcC+ukAUczvlvUuQxrkhF6Qqu6NZ3EirC8H0iFkYU2H++rmLPy8ogDFfrC1EOuTcjQzU/O5FKyfK/3Mejg/TXjdj3hr7H8Zs2oeUC5u9nm9apbBPmShGyTpRXqkoECI1tMbHBx0cKeHvYe/JDIApEXsjhiS0q8P8ZN8rYWuhO4Z1p3YW+isTKyLx3vw3TcBEyXM6MWtUS+HSIKWqSoxPVQ7y7C3PRvFd0LWNwnQ9iQmMpcSh6nnni2LzRukLzaa5m9LXoz2E9mMe/OXPo9nQFMnH99B34WMqaxi7XhqHU1U2CmfSmqUN8NfFbn+1Ocj1mtfgywB2GE9Z/xDU5FPpAY3FxM3jSx845WkKMdycyL/DgXwEkO0YfKvMMs2gAI8NlbP8qxhWO+AW5mVAE82I6ffqQ9MyFd+J/28C+wZAOo91bJmM3ETIuTQ4dMP2vm7CkMUStUP54BXiY/8Nbjfem8NdsOB5GMWGMf2B2T3vrB+rL2ofZ03RADaCrE598ZnUmXXkFaKnc5fPQ1AipFCaDsnPwtPP4DsjmXZO6PMvXmg7l9KGh6Oq/lWxV4F3BpL5cBI4lg4VbSTAJ+C2E31Tdy2k6ZDJAC5z2KZJwuem4AVBlORhs6kuc6b/mg9PzIv3tt1orGQfs1ruALBaPUnHEPPocutSxhYb4S2DxnMhflc6ToQR8avz7BgXhtvRP5Gw/xZ9ZmcWKptvRgtICxroGHD0LVW1+krrLwzwYUJVHAZTeUmahnP+zUBfsHp0ZS1bLi1j+mvSjhjKc3y34sHs+rgTB29cUkwIYb4hJJv465LnTNkAAp4uZ7/t7UdokW9rWtRuCcJHEkQWdDKqwmUWW42BxBQ0tMQLTfS9TKeNcLQ/xAYobyPPYJzZy41ZazkU5ViC9aFFjFCvx6s0txwcvcXvUVDyyEyQcDt27A4aBiHc0jzqZNEZCkMGbG74AmtwKNVZoqAwW4vpvvJzFM91mOElACct63DECUoXueg0+sWsjAVqmbPPaGoWBtTldSIL/4/txzAd2YAUi+/cNzxo2sWQwFXJmnW6pVR+Sf4WCTjp1wv2RTui9cc0S9CjWmYvfwqyEGeQbBa1jnDek2VH0bIokdGREl9Rgy/tt1yTrLb9dbTqWX+yTHUk9A5YtEtvmJ7D9AueLFGKJw8b/2jGMwVKR7SZQ78WPxJKWnz+nhDtbnw7YSo6SS0gOaRZzzcCkQS4QF/8ZuApCGTwT3VdHh/pOw5XHoXx2//z2zkaoVP1792n1DwY3scuyQXbp5LtFQpuCOw0Svgjmzc/l0UKgpXZc6p0WUJDLQhTEpf4OUlzbSMbLb4EUVMSCNtNxXa+B+Q6Zq1F13H7cF4n14sfSbDP/l06CeRuqPEPmhNAepavHqYI5xjqcYpLQOhABRJkJnd9aZEHBmYweS1oAqzj8CsUfae+LQ0alGxq57Unppqxw+VFBKfggG89ChpgkLk2U3oQw4elgcn

init:
  ps: |
        Get-Date
        git config core.autocrlf
        $ErrorActionPreference = "Stop"

install:
  - ps: |
        Import-Module '.\Library.ps1'

build_script:
  - ps: DownloadAndUnpack

test_script:
  - ps: CreateImage

artifacts:
  - path: R.tar.gz R.iso.gz R.vhd.gz
    name: ISO
  - path: R-devel-win.log R-stable-win.log R-packages.log Rtools-current.log
    name: Logs

deploy:
  provider: AzureBlob
  storage_account_name: rportable
  container: r-portable
  storage_access_key:
    secure: 58T9IWbnnWbEPR77jBqYSrXfTP3glkvVoWQ2i2wEFa7EJzU2KYLjdjsoNTPnlzxR0dX2Ao4of8jsZAxSJEm5VjQP4wnRBwV6gwY2DilgLF8zkhUHxAz5s9ZA5HgdYeDK
  folder: $(APPVEYOR_REPO_BRANCH)/$(APPVEYOR_PULL_REQUEST_NUMBER)
  artifact: ISO
